/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qaul_libqaul_LibQaul */

#ifndef _Included_net_qaul_libqaul_LibQaul
#define _Included_net_qaul_libqaul_LibQaul
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qaul_libqaul_LibQaul
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_libqaul_LibQaul_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
